2018-12-22 11:14:28,315[ERROR] 初始化JDBC连接出错 main (rebue.mbgx.plugin.CodeGenByBeetlPlugin:161)
java.sql.SQLException: Column index out of range.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ResultSetMetaData.getField(ResultSetMetaData.java:395) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ResultSetMetaData.getColumnName(ResultSetMetaData.java:243) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at rebue.mbgx.plugin.CodeGenByBeetlPlugin.isMiddleTable(CodeGenByBeetlPlugin.java:354) ~[classes/:?]
	at rebue.mbgx.plugin.CodeGenByBeetlPlugin.initJdbcConn(CodeGenByBeetlPlugin.java:133) [classes/:?]
	at rebue.mbgx.plugin.CodeGenByBeetlPlugin.validate(CodeGenByBeetlPlugin.java:107) [classes/:?]
	at org.mybatis.generator.config.Context.generateFiles(Context.java:502) [mybatis-generator-core-1.3.7.jar:1.3.7]
	at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:269) [mybatis-generator-core-1.3.7.jar:1.3.7]
	at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:139) [mybatis-generator-core-1.3.7.jar:1.3.7]
	at rebue.mbgx.MybatisGeneratorWrap.gen(MybatisGeneratorWrap.java:47) [classes/:?]
	at rebue.ord.gen.OrdGenTest.test(OrdGenTest.java:19) [test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209) [.cp/:?]
2018-12-22 11:14:39,509[ERROR] 初始化JDBC连接出错 main (rebue.mbgx.plugin.CodeGenByBeetlPlugin:161)
java.sql.SQLException: Column index out of range.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ResultSetMetaData.getField(ResultSetMetaData.java:395) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ResultSetMetaData.getColumnName(ResultSetMetaData.java:243) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at rebue.mbgx.plugin.CodeGenByBeetlPlugin.isMiddleTable(CodeGenByBeetlPlugin.java:354) ~[classes/:?]
	at rebue.mbgx.plugin.CodeGenByBeetlPlugin.initJdbcConn(CodeGenByBeetlPlugin.java:133) [classes/:?]
	at rebue.mbgx.plugin.CodeGenByBeetlPlugin.validate(CodeGenByBeetlPlugin.java:107) [classes/:?]
	at org.mybatis.generator.config.Context.generateFiles(Context.java:502) [mybatis-generator-core-1.3.7.jar:1.3.7]
	at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:269) [mybatis-generator-core-1.3.7.jar:1.3.7]
	at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:139) [mybatis-generator-core-1.3.7.jar:1.3.7]
	at rebue.mbgx.MybatisGeneratorWrap.gen(MybatisGeneratorWrap.java:47) [classes/:?]
	at rebue.ord.gen.OrdGenTest.test(OrdGenTest.java:19) [test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209) [.cp/:?]
